# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_title', models.CharField(max_length=30)),
                ('poster_img', models.ImageField(upload_to='poster/post_img/')),
                ('genre', models.CharField(choices=[('art', '미술'), ('photo', '사진'), ('video', '영상'), ('crafts', '공예'), ('piece', '조각'), ('install', '설치'), ('etc', '기타')], default='art', help_text='장르 선택', max_length=50)),
                ('grade', models.IntegerField(choices=[(0, '전체관람가'), (12, '12세이상 관람가'), (15, '15세이상 관람가'), (18, '청소년 관람불가')], default=0, help_text='관람 선택')),
                ('fee', models.IntegerField()),
                ('location', models.CharField(choices=[('seoul', '서울'), ('incheon', '인천'), ('daejeon', '대전'), ('daegu', '대구'), ('ulsan', '울산'), ('gwangju', '광주'), ('chungcheonnam', '충청남도'), ('chungcheonbuk', '충청북도'), ('gyeongsangnam', '경상남도'), ('gyeongsangbuk', '경상북도'), ('jeollanam', '전라남도'), ('jeollabuk', '전라북도'), ('jeju', '제주')], default='seoul', help_text='지역 선택', max_length=50)),
                ('place', models.CharField(max_length=100)),
                ('thumbnail_img_1', models.ImageField(upload_to='poster/thumbnail_1/')),
                ('thumbnail_img_2', models.ImageField(upload_to='poster/thumbnail_2/')),
                ('time_start', models.TimeField(help_text='HH:MM')),
                ('time_end', models.TimeField(help_text='HH:MM')),
                ('date_start', models.DateField(help_text='YYYY-MM-DD')),
                ('date_end', models.DateField(help_text='YYYY-MM-DD')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
