# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
